################################################################################################
# Requirements & Config.
################################################################################################

#-----------------------------------------------
# Build Settings
#-----------------------------------------------
markdown: kramdown
permalink: pretty
exclude: ['README.md', 'LICENSE.txt', 'CNAME']

#-----------------------------------------------
# Plugins
#-----------------------------------------------
plugins_dir:
- jekyll-sitemap
#- jekyll-menus

safe: false

################################################################################################
# Site Settings
################################################################################################
title: "BSidesNYC"
email: "bsides@bsidesnyc.org"
twitterAccount: "@bsidesnyc"
description: "BSides NYC is an Information / Security conference that’s different. We’re a 100% volunteer organized event put on by and for the community, and we truly strive to keep information free."
url: "https://bsidesnyc.org" #https://bsidesnyc.github.io
timezone: "America/New_York"
conYear: "2020"
previousSponsorCount: "13"
previousAttendeeCount: "400"
logoImage: "/about/logo_white.png"
#logoImageHead: "/about/logo_black.png"

#-----------------------------------------------
# Footer
#-----------------------------------------------
socialLinks:
 - {link: "https://twitter.com/bsidesnyc", icon: "twitter"}
 - {link: "https://www.linkedin.com/company/bsidesnyc", icon: "linkedin"}
footerBlocks:
 -
  title: "Links"
  links:
   - {permalink: "/", text: "BSidesNYC"}
   - {link: "http://www.securitybsides.com", text: "Security BSides"}
 -
  title: "Contacts"
  links:
   - {permalink: "/contact/", text: "Contact Us"}
   - {link: "https://bsidesnyc-slack.herokuapp.com", text: "Join our Slack"}
   - {link: "mailto:bsides@bsidesnyc.org", text: "bsides(at)bsidesnyc.org"}
 -
  title: "Policies"
  links:
   - {permalink: "/policies/", text: "CoC & Anti-Harassment"}
 -
  title: "Press"
  links:
   - {permalink: "/press/", text: "Press Release"}
   - {permalink: "/press-pass/", text: "Press Passes"}

#-----------------------------------------------
# Head
#-----------------------------------------------
metaKeywords: "bsides, security, bsidesnyc, conference, nyc"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

#-----------------------------------------------
# Navigation
#-----------------------------------------------
navigationLinks:
 - {permalink: "/about/", text: "About"}
 - {permalink: "/volunteers/", text: "Volunteer"}
#bottomNavigationLinks:
# - {permalink: "/cfp/", text: "Become a speaker"}
#rightNavigationButtons:
# - {permalink: "/volunteers/", text: "Volunteer!"}

################################################################################################
# Block Data
################################################################################################

#-----------------------------------------------
# About
#-----------------------------------------------
aboutTitle: "What is BSidesNYC?"
aboutBlock:
 - {title: "Conference", image: "logo_black.png", text: "BSidesNYC is an Information / Security conference that’s different. We’re a 100% volunteer organized event put on by and for the community and we truly strive to keep information free." }
 - {title: "Villages", image: "toool.png", text: "Rather pick some locks or get hands on with some hardware hacking? We got ya covered." }
 - {title: "CTF", image: "htb.png", text: "Think you have skillz? This year we have two Capture the Flag challenges to help you gain bragging rights and win prizes!" }

#-----------------------------------------------
# Contact
#-----------------------------------------------
contactTitle: "Need to get in touch?"
contactTextTwitter: "Follow us on Twitter"
contactTextEmail: "or email us at"
contactMailingListText: "Just looking to stay in the loop? Use the form below to get announcements on all things BSidesNYC or join our <a href=\"https://bsidesnyc-slack.herokuapp.com\" target=\"_blank\">Slack</a> workspace."
contactVolunteersMailingListText: "Looking to sign up as a volunteer? Head over to our <a href=\"/volunteers/\">volunteers page</a> and sign-up."

#-----------------------------------------------
# Event Intro
#-----------------------------------------------
eventImage: "nyc_skyline.jpg"
eventTitle: "BSidesNYC"
eventDate: "October, 2020"
eventInfo: "The next BSidesNYC will take place in October, 2020.  To stay updated on volunteer opportunities, and other news, follow us on Twitter <a href=\"https://twitter.com/bsidesnyc\" target=\"_blank\">@BSidesNYC</a> and sign up for the mailing list."

#-----------------------------------------------
# Subscribe
#-----------------------------------------------
subscribeImage: #"subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://bsidesnyc.us11.list-manage.com/subscribe/post?u=0538b2c81e2e35a4635056f7f&amp;id=731c810915"
subscribeInfo: "We'll only use your email for BSidesNYC announcements. We respect privacy, and don't provide anyone (including sponsors) with this type of information."

#-----------------------------------------------
# Registration | Tickets
#-----------------------------------------------
# flip this to make a quick change whether we have tickets open or closed
ticketsOpen: false
ticketsOpenDate: "December 13, 2017 10:00:00"
ticketsText: "Unable to expense other, costly conferences?

No worries, at BSidesNYC we strive to make the cost of attendance free."
ticketsUpdateText: "Aw snap - looks like all of our tickets were snatched up! Stay tuned for updates on additional opportunities to grab one."
ticketsNextReleaseDate: "January 9th, 2018 10:00:00"
ticketsNextReleaseText: "Didn't get a ticket during our first round? No need to pout - revisit this page for our next round of tickets on "
# add EventBrite URL to `link` when `ticketsOpen` is set to `true`
ticketsButtons:
 - {link: "https://bsidesnyc.eventbrite.com", text: "Get Tickets!", id: "tickets_button_external"}

#-----------------------------------------------
# Volunteers
#-----------------------------------------------
volunteersTitle: "Want to be involved?"
volunteersText: "We are looking for individuals to help in a variety of areas – are you interested in lending a hand? If so, use the form below to sign-up and we'll reach out to you when the conference nears.


Over email? Join our <a href=\"https://bsidesnyc-slack.herokuapp.com\" target=\"_blank\">Slack</a> workspace instead."
volunteersSubscribeTitle: "Join the Team"
volunteersSubscribeAction: "https://bsidesnyc.us11.list-manage.com/subscribe/post?u=0538b2c81e2e35a4635056f7f&amp;id=d6c9dd00a7"
